# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: layout.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from rpc_service import base_pb2 as base__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name='layout.proto',
    package='',
    syntax='proto2',
    serialized_options=_b('\n\024com.aijia.ai.service'),
    serialized_pb=_b(
        '\n\x0clayout.proto\x1a\nbase.proto\"X\n\rLayoutFeature\x12\x11\n\troom_json\x18\x01 \x02(\t\x12\r\n\x05top_k\x18\x02 \x02(\r\x12\x11\n\troom_type\x18\x03 \x02(\r\x12\x12\n\nmodel_type\x18\x04 \x02(\r\"#\n\x04TopK\x12\x1b\n\x06result\x18\x01 \x03(\x0b\x32\x0b.Int32Array2+\n\x06Layout\x12!\n\x06layout\x12\x0e.LayoutFeature\x1a\x05.TopK\"\x00\x42\x16\n\x14\x63om.aijia.ai.service')
    ,
    dependencies=[base__pb2.DESCRIPTOR, ])

_LAYOUTFEATURE = _descriptor.Descriptor(
    name='LayoutFeature',
    full_name='LayoutFeature',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='room_json', full_name='LayoutFeature.room_json', index=0,
            number=1, type=9, cpp_type=9, label=2,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='top_k', full_name='LayoutFeature.top_k', index=1,
            number=2, type=13, cpp_type=3, label=2,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='room_type', full_name='LayoutFeature.room_type', index=2,
            number=3, type=13, cpp_type=3, label=2,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='model_type', full_name='LayoutFeature.model_type', index=3,
            number=4, type=13, cpp_type=3, label=2,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto2',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=28,
    serialized_end=116,
)

_TOPK = _descriptor.Descriptor(
    name='TopK',
    full_name='TopK',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='result', full_name='TopK.result', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto2',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=118,
    serialized_end=153,
)

_TOPK.fields_by_name['result'].message_type = base__pb2._INT32ARRAY
DESCRIPTOR.message_types_by_name['LayoutFeature'] = _LAYOUTFEATURE
DESCRIPTOR.message_types_by_name['TopK'] = _TOPK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LayoutFeature = _reflection.GeneratedProtocolMessageType('LayoutFeature', (_message.Message,), dict(
    DESCRIPTOR=_LAYOUTFEATURE,
    __module__='layout_pb2'
    # @@protoc_insertion_point(class_scope:LayoutFeature)
))
_sym_db.RegisterMessage(LayoutFeature)

TopK = _reflection.GeneratedProtocolMessageType('TopK', (_message.Message,), dict(
    DESCRIPTOR=_TOPK,
    __module__='layout_pb2'
    # @@protoc_insertion_point(class_scope:TopK)
))
_sym_db.RegisterMessage(TopK)

DESCRIPTOR._options = None

_LAYOUT = _descriptor.ServiceDescriptor(
    name='Layout',
    full_name='Layout',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=155,
    serialized_end=198,
    methods=[
        _descriptor.MethodDescriptor(
            name='layout',
            full_name='Layout.layout',
            index=0,
            containing_service=None,
            input_type=_LAYOUTFEATURE,
            output_type=_TOPK,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_LAYOUT)

DESCRIPTOR.services_by_name['Layout'] = _LAYOUT

# @@protoc_insertion_point(module_scope)
